apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

# namespace: donation-app # using customization transformers instead (which provides more options)
transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: _not_important_here
      namespace: donation-app
    unsetOnly: true

patches:
  - target:
      kind: Gateway
      name: gateway

    patch: |-
      - op: replace
        path: /metadata/annotations/cert-manager.io~1cluster-issuer
        value: "production-cluster-issuer"

  - target:
      kind: Gateway
      name: gateway
    patch: |-
      - op: replace
        path: /spec/listeners/1/hostname
        value: "wosoom.com"
      - op: replace
        path: /spec/listeners/2/hostname
        value: "wosoom.com"

      - op: replace
        path: /spec/listeners/3/hostname
        value: "test.wosoom.com"
      - op: replace
        path: /spec/listeners/4/hostname
        value: "test.wosoom.com"

      - op: replace
        path: /spec/listeners/5/hostname
        value: "api.wosoom.com"
      - op: replace
        path: /spec/listeners/6/hostname
        value: "api.wosoom.com"

      - op: replace
        path: /spec/listeners/7/hostname
        value: "auth.wosoom.com"
      - op: replace
        path: /spec/listeners/8/hostname
        value: "auth.wosoom.com"

      - op: replace
        path: /spec/listeners/9/hostname
        value: "longhorn.k8s.wosoom.com"
      - op: replace
        path: /spec/listeners/10/hostname
        value: "longhorn.k8s.wosoom.com"

      - op: replace
        path: /spec/listeners/11/hostname
        value: "dashboard.k8s.wosoom.com"
      - op: replace
        path: /spec/listeners/12/hostname
        value: "dashboard.k8s.wosoom.com"

      - op: replace
        path: /spec/listeners/13/hostname
        value: "hubble.k8s.wosoom.com"
      - op: replace
        path: /spec/listeners/14/hostname
        value: "hubble.k8s.wosoom.com"

      - op: replace
        path: /spec/listeners/15/hostname
        value: "ory-admin.k8s.wosoom.com"
      - op: replace
        path: /spec/listeners/16/hostname
        value: "ory-admin.k8s.wosoom.com"
