apiVersion: apps/v1
kind: Deployment

metadata:
  name: auth-ui
spec:
  replicas: 1
  minReadySeconds: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    spec:
      containers:
        - name: auth-ui
          image: auth-ui:latest

          ### for debugging purposes:
          # command: ["sleep"]
          # args: ["100000"]
          # securityContext:
          #   runAsUser: 0 # Run as root
          #   privileged: true # Give full system privileges (use only if needed)
          #   allowPrivilegeEscalation: true # Allow sudo-like behavior (if required)
          #   capabilities:
          #     add: ["SYS_ADMIN"] # Add specific root capabilities (adjust as needed)

          ports:
            - containerPort: 4455
              name: http-auth-ui
          # https://github.com/ory/kratos-selfservice-ui-node/tree/master?tab=readme-ov-file#configuration
          env:
            - name: PORT
              value: "4455"
            - name: KRATOS_PUBLIC_URL
              value: "http://kratos-public"
            - name: KRATOS_ADMIN_URL
              value: "http://kratos-admin"
            - name: HYDRA_ADMIN_URL
              value: http://hydra-admin
            - name: KRATOS_BROWSER_URL
              valueFrom:
                configMapKeyRef:
                  name: properties-map-auth-ui
                  key: KRATOS_BROWSER_URL
                  optional: false
            - name: COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  name: secrets-auth-ui
                  key: COOKIE_SECRET
                  optional: false
            # following "__Host-<domain>-x-csrf-token" naming convention for better security
            - name: CSRF_COOKIE_NAME
              valueFrom:
                secretKeyRef:
                  name: secrets-auth-ui
                  key: CSRF_COOKIE_NAME
                  optional: false
            - name: CSRF_COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  name: secrets-auth-ui
                  key: CSRF_COOKIE_SECRET
                  optional: false
            # TODO: remove for production
            - name: DANGEROUSLY_DISABLE_SECURE_CSRF_COOKIES
              value: "true"
            - name: NODE_ENV
              value: "development"
          envFrom:
            - configMapRef:
                name: properties-map-auth-ui # add additional values
            - secretRef:
                name: secrets-auth-ui # implicitely
