apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yml
  - service.yml

# adds labels to all resources (including selector and template fields)
labels:
  - pairs:
      app: auth-ui
    includeSelectors: true

patches:
  # TODO: add proper limits if needed
  # - target:
  #     kind: Deployment
  #     name: auth-ui
  #   patch: |-
  #     apiVersion: apps/v1
  #     kind: Deployment
  #     metadata:
  #       name: _ # required field but not used

  #     spec:
  #       template:
  #         spec:
  #           containers:
  #             - name: auth-ui
  #               resources:
  #                 requests:
  #                   cpu: "10m"
  #                   memory: "20Mi"
  #                 limits:
  #                   cpu: "50m"
  #                   memory: "100Mi"

  # NOTE: taint keys are defined in the Terraform file
  - target:
      kind: Deployment
      name: auth-ui
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: _ # required field but not used

      spec:
        template: 
          spec:  
            tolerations:
              - key: "node.kubernetes.io/role"
                operator: "Equal"
                value: "peak-workloads"
                effect: "NoExecute"
