# development setup with ingress to resolve dns: donation-app.test → ingress-dns → minikube ip  → ingress  → gateway

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
  # - ingress.yml
  - cert-manager-cluster-issuer.yml

# namespace: donation-app # using customization transformers instead (which provides more options)
transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: _not_important_here
      namespace: donation-app
    unsetOnly: true

patches:
  # set namespace if doesn't exist on resource
  # - target:
  #     namespace: default
  #   patch: |-
  #     - op: add
  #       path: /metadata/namespace
  #       value: donation-app

  - target:
      kind: Gateway
      name: gateway
    patch: |-
      - op: replace
        path: /spec/gatewayClassName
        value: "nginx"

### patches for tls certificateRefs
  - target:
      kind: Gateway
      name: gateway
    patch: |-
      - op: replace
        path: /metadata/annotations/cert-manager.io~1cluster-issuer
        value: "selfsigned-issuer"

  - target:
      kind: Gateway
      name: gateway
    patch: |-
      - op: replace
        path: /spec/listeners/1/tls/certificateRefs/0/name
        value: "dev-tls"

  - target:
      kind: Gateway
      name: gateway
    patch: |-
      - op: replace
        path: /spec/listeners/3/tls/certificateRefs/0/name
        value: "dev-tls"

  - target:
      kind: Gateway
      name: gateway
    patch: |-
      - op: replace
        path: /spec/listeners/5/tls/certificateRefs/0/name
        value: "dev-tls"

  - target:
      kind: Gateway
      name: gateway
    patch: |-
      - op: replace
        path: /spec/listeners/7/tls/certificateRefs/0/name
        value: "dev-tls"

  - target:
      kind: Gateway
      name: gateway
    patch: |-
      - op: replace
        path: /spec/listeners/9/tls/certificateRefs/0/name
        value: "dev-tls"

  - target:
      kind: Gateway
      name: gateway
    patch: |-
      - op: replace
        path: /spec/listeners/11/tls/certificateRefs/0/name
        value: "dev-tls"

  - target:
      kind: Gateway
      name: gateway
    patch: |-
      - op: replace
        path: /spec/listeners/13/tls/certificateRefs/0/name
        value: "dev-tls"

  - target:
      kind: Gateway
      name: gateway
    patch: |-
      - op: replace
        path: /spec/listeners/15/tls/certificateRefs/0/name
        value: "dev-tls"

