apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

images:
  - name: auth-token-exchange
    newTag: latest

# configMapGenerator:
#   - name: properties-map-auth-token-exchange
#     env: config.properties

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: auth-token-exchange
        
      spec:
        template:
          spec:
            containers:
            - name: auth-token-exchange
              imagePullPolicy: Never

  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: auth-token-exchange

      spec:
        replicas: 1
