apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

# namespace: auth # using customization transformers instead (which provides more options)
transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: _not_important_here
      namespace: auth
    unsetOnly: true

images:
  - name: auth-ui
    newTag: latest

configMapGenerator:
  - name: properties-map-auth-ui
    namespace: auth
    env: .env.development

secretGenerator:
  - name: secrets-auth-ui
    namespace: auth
    envs:
      - secret.env.development

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: auth-ui
        
      spec:
        template:
          spec:
            containers:
            - name: auth-ui
              imagePullPolicy: Never

  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: auth-ui

      spec:
        replicas: 1
