apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

patches:
  - target:
      kind: HTTPRoute
      name: https-k8s-ory-admin
    patch: |-
      - op: replace
        path: /spec/hostnames/0
        value: "ory-admin.k8s.wosoom.com"

  - target:
      kind: HTTPRoute
      name: http-k8s-ory-admin-redirect
    patch: |-
      - op: replace
        path: /spec/hostnames/0
        value: "ory-admin.k8s.wosoom.com"
